language: cpp

dist: artful
sudo: required

matrix:
  include:

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libboost-dev', 'libgtest-dev']

    - os: linux
      compiler: gcc
      env: COMPILER=g++-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libboost-dev', 'libgtest-dev']

    - os: linux
      compiler: clang
      env: COMPILER=clang++-5.0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-artful-5.0']
          packages: ['clang-5.0', 'g++-6', 'libboost-dev', 'libgtest-dev']

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode9


script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version

  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release -- -j4
  - ./jinja2cpp_tests
  - cd ..