language: cpp

dist: artful
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-7', 'libboost-dev', 'libgtest-dev']

before_install:
  - eval "${MATRIX_EVAL}"
    
script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version

  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release -- -j4
  - ./jinja2cpp_tests
  - cd ..
